import {
  Box,
  Container,
  Flex,
  Grid,
  Heading,
  Icon,
  Stack,
  Text,
} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card";
import SkillCard from "../components/Card";
import ToolIcon from "../components/ToolIcon";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Container maxW={"container.lg"} marginTop={[5, 10]}>
          <Flex alignItems={"center"} flexDirection={["column-reverse", "row"]}>
            <Container>
              <Heading
                size={"3xl"}
                textAlign={["center", "left"]}
                marginTop={[5, 0]}
              >
                Little details make the difference.
              </Heading>
              <Text marginTop={2} textAlign={["center", "left"]}>
                I'm David Rivera Morales, a software developer from Mexico who
                enjoys designing, developing and thinking applications in a way
                people can exchange information in various manners.
              </Text>
            </Container>

            <Image
              src={"https://i.imgur.com/isonvRX.png"}
              width={300}
              height={300}
            ></Image>
          </Flex>
          <Container marginTop={14} maxW="container.lg">
            <Heading size={"2xl"} textAlign={"center"}>
              Tools I use
            </Heading>

            <Stack
              direction="row"
              justifyContent={"center"}
              marginTop={5}
              paddingRight={10}
              paddingLeft={10}
            >
              <ToolIcon tool="react"></ToolIcon>
              <ToolIcon tool="flutter"></ToolIcon>
              <ToolIcon tool="nodejs"></ToolIcon>
              <ToolIcon tool="solidity"></ToolIcon>
            </Stack>
          </Container>
          <Container marginTop={14} maxW="xl">
            <Heading size={"2xl"} textAlign={"center"}>
              Projects & Work
            </Heading>
            <Grid templateColumns={["repeat(1,1fr)", "repeat(2, 1fr)"]} gap={4}>
              <Card></Card>
              <Card></Card>
              <Card></Card>
              <Card></Card>
              <Card></Card>
            </Grid>
          </Container>
        </Container>
      </main>
    </div>
  );
}
